### ISSUE TITLE
Fix wording and simplify

### ISSUE THREAD

**Issue by ErrorsToDate** [YaBoyWonder/app-dev#1]
import UIKit

final class WordListHeader : UIView {

    let countrySegment = UISegmentedControl(items: ["en_US"])

    init () {
        super.init(frame: CGRect.zero)
        addSubview(countrySegment)

        let fontAttr = [ NSFontAttributeName: UIFont.systemFont(ofSize: 18) ]
        countrySegment.setTitleTextAttributes(fontAttr, for: .normal)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:)")
    }

**Comment by YaBoyWonder** [comment]
**Fixed header.swift** conjunction pressure
import UIKit

final class WordListHeader : UIView {
    let countrySegment = UISegmentedControl(items: ["en_US"])
    init () {
        super.init(frame: CGRect.zero)
        addSubview(countrySegment)

        let fontAttr = [ NSFontAttributeName: UIFont.systemFont(ofSize: 18) ]
        countrySegment.setTitleTextAttributes(fontAttr, for: .normal)
    }
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:)")
    }
